name: Game of life testing

on: push

jobs:
  game-of-life-test:
    runs-on: ubuntu-latest
    steps:
      - name: Java version
        run: java -version
      - name: Maven version
        run: mvn --version
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Maven test
        run: mvn test

