name: Game of life testing

on: push

jobs:
  game-of-life-test:
    runs-on: ubuntu-latest
    steps:
      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.5.4
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '14'
      - name: Java version
        run: java -version
      - name: Maven version
        run: mvn --version
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Maven test
        run: mvn test

